services:
  app:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp:
